### ISSUE TITLE
we should add this notebook to the repo

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/Python-course-materials-for-seismology-students#2]
https://www.google.com/url?q=https://github.com/mnky9800n/python_for_hazard_scientists/blob/master/introduction%2520to%2520python.ipynb&sa=D&ust=1507280263392000&usg=AFQjCNGn7f2G6ilCEEU1rmYOXDX0CwqOvQ

**Comment by seismoChas** [comment]
I have added this to the cartopy branch.
