### ISSUE TITLE
we should add this notebook to the repo

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/Python-course-materials-for-seismology-students#3]
https://www.google.com/url?q=https://github.com/mnky9800n/python_for_hazard_scientists/blob/master/testing%2520python.ipynb&sa=D&ust=1507280304708000&usg=AFQjCNGeUCdGx2GLOBrLlmWO4b8apwSzAQ

**Comment by seismoChas** [comment]
I added a basemap and cartopy version of this since basemap and cartopy do not play well together in the same environment.
