### ISSUE TITLE
introduction to reading data and plotting using pandas should use seismology data

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/Python-course-materials-for-seismology-students#5]
originally i made this using bicycle data because i got it from somewhere else. this bicycle data is sort of nonsensical for a seismology course so we should replace it with a catalog or something else.

**Comment by seismoChas** [comment]
I re-wrote this notebook to use Southern California earthquake catalog data. I would have used the ANSS but it is extremely ugly for trying to illustrate a broken dataframe. So I used the Southern California earthquake catalog instead.
