### ISSUE TITLE
Making maps and calculating statistics for a region

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/Python-course-materials-for-seismology-students#6]
this needs to have more explanations for each code block

**Comment by seismoChas** [comment]
The data set used in this example doesn't exist. Care to suggest another data set to use?

Is the plotting function in utilities just for basemap? So we will need to add functions for plotting in cartopy?!

**Comment by mnky9800n** [comment]
Actually, this is a shitty notebook that should be deleted.
