### ISSUE TITLE
Maps for unshaped data using cartopy needs more explanation

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/Python-course-materials-for-seismology-students#7]
I go back and forth on this one, I think all of the notebooks should have some explanation but this one seems obvious to me, but I am not a student.

**Comment by mnky9800n** [comment]
like especially the gridding data and interpolation should have an explanation as to what that is and why its important to have interpoloation or not have it.

**Comment by seismoChas** [comment]
We could have a separate section that teaches how your style choice of interpolation affects the result. Something like this: https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.interpolate.griddata.html

**Comment by mnky9800n** [comment]
Maybe? Maybe just reference that link. We have to remember one of the goals of the library is to provide scaffolding for starting projects, not to communicate everything there is to know about everything.

**Comment by seismoChas** [comment]
I like the idea of just providing a link and letting the students explore that more on their own.

**Comment by seismoChas** [comment]
I have updated this notebook with more explanation about gridding and interpolation. I also made a function called "basic_Japan_map" that is used over and over again in the notebook. I think it was just a waste to repeatedly write the same code. And students should learn how useful functions can be for repeated tasks.
