### ISSUE TITLE
should we remove all of the "cartopy" names from the notebooks

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/Python-course-materials-for-seismology-students#8]
I want to suggest using cartopy as the default for the course materials since basemap is dying. Maybe in the paper

**Comment by seismoChas** [comment]
My point in adding the labels "basemap" and "cartopy" is to distinguish the notebooks... in the case that people download both. I think maybe your point is rather should we just remove the basemap ipython notebooks instead (i.e. keeping only cartopy)?

**Comment by mnky9800n** [comment]
I guess, whatever you think is best is best. I suggest finalizing the cartopy branch, merging with the master, then we set a roadmap for basemap to be removed.
