### ISSUE TITLE
can we come up with a better name than "seismology tools"?

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/Python-course-materials-for-seismology-students#9]
it doesn't really describe what the library does since seismology is so broad. it would be better with a more descriptive name.

**Comment by seismoChas** [comment]
Python for seismologists?

**Comment by mnky9800n** [comment]
That is really broad still. What does the library do? Right now it provides an introduction to python mapping and data analysis mostly for people interested in doing stuff with catalogs. It doesn't do anything else like waveforms or anything like that. It's sort of complicated. We could always call it something dumb like "fazer-dazer" but I would prefer something descriptive but no restrictive.

**Comment by seismoChas** [comment]
Intro to Python: mapping and data analysis ?

**Comment by seismoChas** [comment]
What about "Python course materials for seismology students"?

**Comment by mnky9800n** [comment]
Well, that is okay i guess.

**Comment by mnky9800n** [comment]
i renamed it to "Python-course-materials-for-seismology-students"

**Comment by seismoChas** [comment]
=D
